env:
  browser: true
  es2022: true
  jest: true
extends: [eslint:recommended, prettier]
plugins: [prettier]
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  prettier/prettier: [error]
